services:
  seismotracker-mongo:
    image: mongo:latest
    container_name: seismotracker-mongo
    volumes: 
      - /project/seismotracker/data/mongo:/data/db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: endoplazmikretikulum
    networks:
      - seismotracker-network
    labels:
      com.centurylinklabs.watchtower.enable: true

  seismotracker-fetcher:
    image: seismotracker-fetcher:latest
    build:
      context: ./seismotracker
      dockerfile: Dockerfile
    container_name: seismotracker-fetcher
    restart: always
    depends_on:
      - seismotracker-mongo
    environment:
      MONGO_URI: mongodb://root:endoplazmikretikulum@seismotracker-mongo:27017
    networks:
      - seismotracker-network
    labels:
      com.centurylinklabs.watchtower.enable: false

  seismotracker-lightdash:
    image: seismotracker-lightdash:latest
    build:
      context: ./lightdash
      dockerfile: dockerfile
    restart: always
    container_name: seismotracker-lightdash
    env_file:
      - ./lightdash/.env
    depends_on:
      - seismotracker-postgres-lightdash
    environment:
      - PGHOST=${PGHOST:-db}
      - PGPORT=${PGPORT:-5432}
      - PGUSER=${PGUSER:-postgres}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE:-postgres}
      - SECURE_COOKIES=${SECURE_COOKIES:-false}
      - TRUST_PROXY=${TRUST_PROXY:-false}
      - LIGHTDASH_SECRET=${LIGHTDASH_SECRET}
      - PORT=${PORT:-8080}
      - LIGHTDASH_LOG_LEVEL=${LIGHTDASH_LOG_LEVEL}
      - LIGHTDASH_INSTALL_ID=${LIGHTDASH_INSTALL_ID}
      - LIGHTDASH_INSTALL_TYPE=${LIGHTDASH_INSTALL_TYPE:-docker_image}
      - AUTH_DISABLE_PASSWORD_AUTHENTICATION=${AUTH_DISABLE_PASSWORD_AUTHENTICATION}
      - AUTH_ENABLE_GROUP_SYNC=${AUTH_ENABLE_GROUP_SYNC}
      - AUTH_GOOGLE_ENABLED=${AUTH_GOOGLE_ENABLED}
      - AUTH_GOOGLE_OAUTH2_CLIENT_ID=${AUTH_GOOGLE_OAUTH2_CLIENT_ID}
      - AUTH_GOOGLE_OAUTH2_CLIENT_SECRET=${AUTH_GOOGLE_OAUTH2_CLIENT_SECRET}
      - SITE_URL=${SITE_URL}
      - EMAIL_SMTP_HOST=${EMAIL_SMTP_HOST}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL_SMTP_SECURE=${EMAIL_SMTP_SECURE}
      - EMAIL_SMTP_USER=${EMAIL_SMTP_USER}
      - EMAIL_SMTP_PASSWORD=${EMAIL_SMTP_PASSWORD}
      - EMAIL_SMTP_ALLOW_INVALID_CERT=${EMAIL_SMTP_ALLOW_INVALID_CERT}
      - EMAIL_SMTP_SENDER_NAME=${EMAIL_SMTP_SENDER_NAME}
      - EMAIL_SMTP_SENDER_EMAIL=${EMAIL_SMTP_SENDER_EMAIL}
      - ALLOW_MULTIPLE_ORGS=${ALLOW_MULTIPLE_ORGS:-false}
      - LIGHTDASH_QUERY_MAX_LIMIT=${LIGHTDASH_QUERY_MAX_LIMIT}
      - LIGHTDASH_MAX_PAYLOAD=${LIGHTDASH_MAX_PAYLOAD:-5mb}
      - HEADLESS_BROWSER_HOST=headless-browser
      - HEADLESS_BROWSER_PORT=3000
      - RUDDERSTACK_WRITE_KEY=${RUDDERSTACK_WRITE_KEY}
      - SCHEDULER_ENABLED=true
      - GROUPS_ENABLED=${GROUPS_ENABLED:-false}
      - POSTHOG_PROJECT_API_KEY=${POSTHOG_PROJECT_API_KEY}
      - POSTHOG_FE_API_HOST=${POSTHOG_FE_API_HOST}
      - POSTHOG_BE_API_HOST=${POSTHOG_BE_API_HOST}
    volumes:
      - /project/seismotracker/lightdash:/usr/app/dbt
    ports:
      - ${PORT:-8080}:${PORT:-8080}
    networks:
      - seismotracker-network
    labels:
      com.centurylinklabs.watchtower.enable: false

  seismotracker-postgres-lightdash:
    image: postgres:15.4
    restart: always
    container_name: seismotracker-postgres-lightdash
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_DB: ${PGDATABASE:-postgres}
    volumes:
      - /project/seismotracker/data/postgres-lightdash:/var/lib/postgresql/data
    networks:
      - seismotracker-network
    labels:
      com.centurylinklabs.watchtower.enable: true

  seismotracker-headless-browser:
    image: ghcr.io/browserless/chromium:v2.24.3
    restart: always
    container_name: seismotracker-headless-browser
    ports:
      - 3001:3000
    networks:
      - seismotracker-network
    labels:
      com.centurylinklabs.watchtower.enable: true


networks:
  seismotracker-network:
    name: seismotracker-network
    driver: bridge
