kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: seismo
nodes:
  - role: control-plane
    image: kindest/node:v1.32.2
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
    kubeadmConfigPatches:
    - |
      kind: ClusterConfiguration
      apiServer:
        extraArgs:
          enable-admission-plugins: NodeRestriction,AlwaysPullImages,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
  - role: worker
    image: kindest/node:v1.32.2
  - role: worker
    image: kindest/node:v1.32.2
networking:
  disableDefaultCNI: false
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443