name: Build and Push Multi-Arch Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: lightdash
            dockerfile: dockerfile
          - service: seismotracker
            dockerfile: Dockerfile

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.MY_PAT_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build and Push Multi-Arch Image
        run: |
          cd ${{ matrix.service }}
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ghcr.io/konamata/${{ matrix.service }}:latest \
            -f ${{ matrix.dockerfile }} . --push