name: Build and Push Multi-Arch Docker Images

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '#BUILD')
    strategy:
      matrix:
        services:
          - name: lightdash
            folder: lightdash
            dockerfile: Dockerfile
      max-parallel: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Copy Dockerfile to Submodule
        run: |
          cp -v lightdash_docker/Dockerfile lightdash/Dockerfile

      - name: Set up QEMU and Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_PAT_TOKEN }}

      - name: Generate Unique Tag
        id: unique_tag
        run: |
          UNIQUE_TAG="build-${{ github.run_id }}-$(date +%s)"
          echo "Generated unique tag: $UNIQUE_TAG"
          echo "unique_tag=$UNIQUE_TAG" >> $GITHUB_OUTPUT

      - name: Build and Push Multi-Arch Image (No Cache)
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.services.folder }}
          file: ${{ matrix.services.folder }}/${{ matrix.services.dockerfile }}
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.services.name }}:${{ steps.unique_tag.outputs.unique_tag }}
            ghcr.io/${{ github.repository }}/${{ matrix.services.name }}:latest
          no-cache: true