name: Lightdash CI/CD

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push-arm64:
    runs-on: ubuntu-22.04-arm
    if: contains(github.event.head_commit.message, '#LIGHTDASH')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up QEMU and Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_PAT_TOKEN }}

      - name: Build and Push ARM64 Image (No Cache)
        uses: docker/build-push-action@v6
        with:
          context: lightdash
          file: lightdash/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/lightdash:arm64
          no-cache: true
          provenance: false

  build-and-push-amd64:
    runs-on: ubuntu-24.04
    if: contains(github.event.head_commit.message, '#LIGHTDASH')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up QEMU and Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_PAT_TOKEN }}

      - name: Build and Push AMD64 Image (No Cache)
        uses: docker/build-push-action@v6
        with:
          context: lightdash
          file: lightdash/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}/lightdash:amd64
          no-cache: true
          provenance: false

  create-manifest:
    runs-on: ubuntu-24.04
    needs: [build-and-push-arm64, build-and-push-amd64]
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_PAT_TOKEN }}

      - name: Create Multi-Arch Image Manifest
        run: |
          docker manifest create ghcr.io/${{ github.repository }}/lightdash:latest \
            ghcr.io/${{ github.repository }}/lightdash:arm64 \
            ghcr.io/${{ github.repository }}/lightdash:amd64
          docker manifest push ghcr.io/${{ github.repository }}/lightdash:latest