name: Update Submodules

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches:
      - main

env:
  HAS_CHANGES: false

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.MY_PAT_TOKEN }}

      - name: Update all submodules to the latest commit
        run: |
          git submodule update --remote --recursive
          git status

      - name: Check for changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Submodules have updates."
            echo "HAS_CHANGES=true" >> $GITHUB_ENV
          else
            echo "No updates found."
            echo "HAS_CHANGES=false" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.HAS_CHANGES == 'true'
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Auto-update submodules to latest commit"
          git push origin main